<?php
/**
 * Category sidebar
 *
 * @var $block Sebwite\Sidebar\Block\Sidebar
 */
$categories = $block->getCategories();

// Loop through categories
foreach($categories as $category) {

    // Echo parent category
    echo '<h4><a href="' . $block->getCategoryUrl($category) . '" title="' . $category->getName() . '">' . $category->getName() . '</a></h4>';

    // Check if category has children
    if($category->hasChildren()) {

        $childCategories = $block->getSubcategories($category);

        if(count($childCategories) > 0) {

            echo '<ul class="o-list o-list--unstyled">';
            // Loop through children categories
            foreach($childCategories as $childCategory) {
                printHtml($childCategory, $block);

            }
            echo '</ul>';
        }
    }
}

function printHtml($category, $block) {
    echo '<li ' . (($block->isActive($category) == true) ? 'class="is-active"' : '') . ' >';
    echo '<a href="' . $block->getCategoryUrl($category) . '" title="' . $category->getName() . '">' . $category->getName() . '</a>';

    $childCategories = $block->getSubcategories($category);
    if(count($childCategories) > 0) {

        echo '<ul class="o-list o-list--unstyled">';
        foreach($childCategories as $childCategory) {
            printHtml($childCategory, $block);
        }
        echo '</ul>';
    }
    echo '</li>';
}